### ISSUE TITLE
Bad instances display on deploying instances

### ISSUE THREAD

**Issue by alexandrebrg** [CleverCloud/clever-components#1070]
Hi :wave: 

I was deploying a new clever app, I failed to deploy it properly several times, after a few run the list of instances shown inside the new console interface wasn't showing names properly. 

I opened the logs after the few failed run during a new deployment, after that new instances (even running) shown wrongly:
![image](https://github.com/CleverCloud/clever-components/assets/23573685/58c1a84a-77f7-4c07-9e9f-981dee730834)

When refreshing with one fully running instance, I still have stuff going wrong:
![image](https://github.com/CleverCloud/clever-components/assets/23573685/f65d728e-a7a3-42aa-a8e6-75b710156295)

As the bug can be reproduced on my name, i can give some requests logs or anything to help :)

**Comment by Bencaddyro** [comment]
Same problem on my side 
![image](https://github.com/CleverCloud/clever-components/assets/17800864/261bd9ce-2377-47ba-8303-c8edcf1fde9b)
also happened after a failed deployement

**Comment by pdesoyres-cc** [comment]
This happens when the instance state is not known. As of now, we know about the following states:

'BOOTING', 'STARTING', 'DEPLOYING', 'READY', 'UP', 'MIGRATION_IN_PROGRESS', 'TASK_IN_PROGRESS', 'BUILDING', 'STOPPING', 'DELETED', 'WORK_IN_PROGRESS'

The question is: does the API can return some other state that we are not aware of?
