### ISSUE TITLE
[server list] Safari can't handle the scroll on the right panel 

### ISSUE THREAD

**Issue by cnivolle** [CleverCloud/clever-components#160]
On `cc-input-zones` (default) in Safari, the server list on the right is not scrollable, unlike other browsers.
When selecting or hovering an icon, the scrolling effect occurs abruptly on the list, creating a glitchy effect on the component and making the selection quite hazardous.

Also, the touch on markers doesn't work either on iOS (tested on the iPad and iPhone). The right view is scrollable on the iPhone.

Here's a live example ( ⚠️ 9 MB GIF ):

![SmallerStickAround](https://user-images.githubusercontent.com/204502/92480696-8f2b3600-f1e5-11ea-963c-b7bb2537bf9a.gif)

**Comment by hsablonniere** [comment]
OK, let's list the problems:

* the server list on the right is not scrollable on Safari 13, desktop and iPad (works in Safari 14)
* When selecting or hovering an icon, the scrolling effect occurs abruptly on the list, creating a glitchy effect on the component and making the selection quite hazardous.
  * This is because they don't support options for `scrollIntoView` https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView
* The touch on markers doesn't work either on iOS

**Comment by hsablonniere** [comment]
Fixed in #163
