### ISSUE TITLE
cc-orga-members: init component

### ISSUE THREAD

**Issue by hsablonniere** [CleverCloud/clever-components#373]
# Main user needs:

1. Inviting new members to org
2. Removing members from an org (One at a time).
3. Editing member role (One at a time). This means it should also be easy to **view rights related to each role**.
4. Checking / Viewing who’s in the org, their role, etc.. **See who activated 2 Factor Auth or not**.

**Comment by florian-sanders-cc** [comment]
# Questions:

## Viewing Members

- is job title of any use ? Might be confusing (different with “roles”).  ⇒ check metabase to see it is actually used by orgs.
- sorting and filtering features ? ⇒ check metabase to see the number of members per org + org with the highest member count
- if an org only has one member, disable edit of role (can only be admin) + removal feature ? (check with Arnaud or Marc Antoine)
- rule to enforce that there is at least one admin in the org ? (should be done API side also) (check with Arnaud or Marc Antoine)
- should we display how many members are in the team ? (seems easy to do so IMO yes) ⇒ **yes**

## Editing member info

- email ⇒ should we really keep that feature (which is currently broken anyway). IMO ⇒ org admin should not be able to edit this type of info. If needed they may remove user to invite with another e-mail or user can change its e-mail by himself (is it currently possible though ?) (check with Arnaud or Marc Antoine)
- role ⇒ essential. Should this be done with or without validation ? ⇒ with validation

## Removing members

- should it require user confirmation ? Since there is no data loss and users can be reinvited right after being removed, it may not be necessary to ask for confirmation. ⇒ **Provide some delay to cancel action (3 to 5 seconds should be enough)**.

## Inviting members

- what if user is already in ? message to warn but where ? ⇒ **test current implementation**

**Comment by florian-sanders-cc** [comment]
# Decisions

## Viewing Members
- No job title field to fill anymore. Job titles already set in the API will only be visible when hovering user name,
- sorting: ?
- Filtering: ?
- If an org only has one member remove edit and user deletion features.
- Rule to enforce that there is at least one admin in the org: ?
- Display how many members are in the team (next to the heading introducing the block)

## Editing member info
- email: org admins cannot modify email of a user (same as right now even though it seems confusing with the current interface)
- role: can be edited but requires the user to validate their action. Provide an edit button to toggle edit mode. Provide a cancel and validate buttons when in edit mode.

## Removing members
- Button with some delay to cancel action (3 to 5 seconds should be enough).

## Inviting members
- user already is in the org: ?
- pending invites: ?
