### ISSUE TITLE
Discussion: Improve icon system

### ISSUE THREAD

**Issue by hsablonniere** [CleverCloud/clever-components#436]
## Context

We started with basic SVG icons, one file per icon.
It worked pretty well until recently.

* We're introducing design tokens and soon a dark mode
  * how do we handle a light mode + dark mode version with our current system?
* Even without talking about dark mode, when you need different shades of the same icon, right now we have 2 files

## Ideas

* Maybe we should move from `<img src="foo.svg">` to inlined SVG
* We won't be able to use `use` as it does not work with Shadow DOM
* Not really related but this would be a good opportunity to scale all our icons to the same dimensions (and other settings)

Moving to inlined SVGs would have a lot of implications on the build system and our components, we need to list detailed pros and cons.

**Comment by roberttran-cc** [comment]
Related link: https://remixicon.com/

**Comment by roberttran-cc** [comment]
# Thinking the upcoming icon system

## Goals

Improve icon managment in our products by having:
- an unified icon library,
- an icon component:
  - capable of loading icon from the library,
  - allowing customization (size, color, and more?).

Resulting in a better developer experience:
- faster integration,
- safer integration.

And a better user experience:
- homogeneity,
- diversity.

## File Format

It seems there's a consensus on the **SVG format** for icons in term of integration and rendering:
- https://css-tricks.com/icon-fonts-vs-svg/
- https://fontawesome.com/v6/docs/web/dig-deeper/webfont-vs-svg
- https://betterprogramming.pub/inline-svg-or-icon-fonts-which-one-to-use-77c0daf1c527
- https://developer.mozilla.org/en-US/docs/Web/SVG

Note: maybe there's a case for CSS icons with... [CSS icons](https://css.gg/) (MIT License)?

## Icon Library

### What kind of library?

Whatever library that:
- matches our branding,
- provides professional-looking icons,
- provides a sufficient amount of icons,
- provides SVG icons (ideally squared icons & easlily customisable),
- allows commercial use.

### Which library?

Some candidates.

| Name             | Icons count   | License            | URL                                              |
| ---------------- | ------------- | ------------------ | ------------------------------------------------ |
| Remix Icon       | `2271 icons`  | Apache License 2.0 | https://remixicon.com/                           |
| Material Symbols | `2500+ icons` | Apache License 2.0 | https://github.com/google/material-design-icons/ |
| Basicons         | `322 icons`   | MIT License        | https://basicons.xyz/                            |
| heroicons        | `230 icons`   | MIT License        | https://heroicons.com/                           |
| Tabler icons     | `2052 icons`  | MIT License        | https://tabler-icons.io/                         |

## Implementation

Obviously, the icon component will be a part of the [Clever Components](https://github.com/CleverCloud/clever-components/): `<cc-icon></cc-icon>`.

Note: component style may vary depending on the SVG structure (for proper customisation, see below).

### Inputs

| Property | Type           | Description                           |
| -------- | -------------- | ------------------------------------- |
| `size`   | `String\|null` | sizes available: `xs\|sm\|md\|lg\|xl` |
| `icon`   | `String\|null` | icon identifier from a resolver       |
| `<slot>` | `String`       | SVG icon                              |

More inputs: flip? badge? label (for a11y)?

### CSS custom properties

| Property    | Target                           | Description                      |
| ----------- | -------------------------------- | -------------------------------- |
| `--size`    | `width`, `height`                | change the icon width and height |
| `--color`   | `fill`, `stroke`, `currentColor` | change the icon color            |

More properties: opacity?

Note: `font-size (em|rem)` instead of `width|height`?

### On resolver

Implemented in:
- [Clarity](https://clarity.design/icons/api)
- [Lion](https://lion-web.netlify.app/fundamentals/systems/icon/overview/)
- [Nord](https://nordhealth.design/components/icon/)
- [Shoelace](https://shoelace.style/components/icon?id=icon-libraries)

Goal:
- display an icon from his id

Needs:
- wrapping SVG as strings or template literals
- sanitizing

Allows:
- flexibility
- tree shaking benefit (when sync)

Eventually:
- namespaces
- aliases creation
- mutator function (see Shoelace)
- async/cdn loading (smart CDN like?)

## Some examples under the hood

| Design System | Company      | URL                                       |
| ------------- | ------------ | ----------------------------------------- |
| Lightning     | Salesforce   | https://www.lightningdesignsystem.com/    |
| Lion          | ING Bank     | https://lion-web.netlify.app/             |
| Vitamin       | Decathlon    | https://github.com/Decathlon/vitamin-web/ |
| Clarity       | VMware       | https://clarity.design/                   |
| Nord          | Nordhealth   | https://nordhealth.design/                |
| Shoelace      | Cory LaViska | https://shoelace.style/                   |

<details>
<summary>Lightning</summary>
Icons: raw SVG ; SVG sprites.<br>
Component: HTML/CSS (no JS) ; underlying CSS custom property.
</details>

<details>
<summary>Lion</summary>
Icons: raw SVG ; wrapped (literal) ; provided via a resolver (sync/async).<br>
Component: Web Component on top of Lit ; `IconManager.js` resolver class.
</details>

<details>
<summary>Vitamin</summary>
Icons: raw SVG ; SVG sprite ; icon font.<br>
Component: HTML/CSS (no JS).
</details>

<details>
<summary>Clarity</summary>
Icons: raw SVG ; wrapped (string) ; provided via a resolver (sync).<br>
Component: Web Component on top of Lit ; `ClarityIcons.js` resolver class.
</details>

<details>
<summary>Nord</summary>
Icons: raw SVG ; wrapped (string) ; provided via a resolver (sync/async/cdn).<br>
Component: Web Component on top of Lit ; icon component static functions.
</details>

<details>
<summary>Shoelace</summary>
Icons: raw SVG ; no wrapping, SVG file load ; provided via a resolver (async/cdn).<br>
Component: Web Component on top of Lit ; `icon-library.js` resolver class.
</details>

## Accessibility

Some examples:

- https://www.lightningdesignsystem.com/components/icons/#Accessibility
- https://lion-web.netlify.app/fundamentals/systems/icon/overview/#icon-accessibility
- https://clarity.design/icons/accessibility

## Wrapping up

Implemetation is a matter of developer experience (almost exclusively).

Rely on raw SVG.

Use a resolver.

Allow custom icon with the `<slot></slot>`.

Eventually export icon font or sprite.

## Miscellaneous

To do:
- write an ADR

On iconography:
- https://www.lightningdesignsystem.com/guidelines/iconography/

On performance:
- https://twitter.com/techytacos/status/1537105768629010432

Other approach
- https://backlight.dev/blog/how-to-manage-icons-in-your-UI-library-part-1

**Comment by roberttran-cc** [comment]
Issue for technical implementation at #525. Closing this discussion!
