### ISSUE TITLE
eslint configuration not handling unassigned imports

### ISSUE THREAD

**Issue by roberttran-cc** [CleverCloud/clever-components#775]
Little reminder:
```js
// this is an unassigned import
import '../cc-button/cc-button.js';
```

Although all other imports are correctly sorted, unassigned imports are not checked and there are some disparities between components: in one component, unassigned imports are coded before all imports, in an another, they are coded after.

We use the `eslint-plugin-import` [plugin](https://github.com/import-js/eslint-plugin-import) which [clearly state](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md):

> Unassigned imports are ignored, as the order they are imported in may be important.

And it seems this behavior won't be considered [anytime soon](https://github.com/import-js/eslint-plugin-import/issues/1084) by this plugin.

Maybe consider testing the `sort-imports` [rule](https://eslint.org/docs/latest/rules/sort-imports) built in `eslint`, especially the `membersyntaxsortorder` [option](https://eslint.org/docs/latest/rules/sort-imports#membersyntaxsortorder).

Note: the `eslint-plugin-simple-import-sort` dependency in our `package.json` is not used, we can remove it as part of this issue.

**Comment by florian-sanders-cc** [comment]
@roberttran-cc I didn't know about this issue but this is very clear and well documented, gg! :clap: 

If it's ok with you I'll close it because the import order is now handled by prettier thanks to @Galimede!

Also, the `eslint-plugin-simple-import-sort` is still in our deps even though we don't use it (:see_no_evil:) but I've removed it from the project within the eslint flat config migration PR :+1:

(feel free to reopen if you think I've missed something)
