### ISSUE TITLE
CDN UI (release): list versions in semver order

### ISSUE THREAD

**Issue by florian-sanders-cc** [CleverCloud/clever-components#803]
## Context

Currently the CDN (release) lists the version `7.13.1` first because it was the last version created.

Versions should be listed in semver order to avoid this.

Question: should it be done by the client (CDN UI) or the worker directly within the manifest? Or both?

**Comment by roberttran-cc** [comment]
I'll go with both:
- in the worker because the manifest should be the source of truth & the semver order is the order that makes most sense I guess
- in the CDN UI to make this order explicit (and indicate it can be overridden later for some reason)

**Comment by pdesoyres-cc** [comment]
- in the CDN UI, certainly
- in the manifest, not mandatory but it's easy to do as well so why not. We'll just need to reorder it manually.

**Comment by hsablonniere** [comment]
In the CDN UI. It was sorted by semver in the manifest because it came from GitHub and that's how it was sorted. Now that we append new versions, we have this. Sorting in the UI will prevent future problems.

:cry: I guess it means we have to load the semver dep in the UI just for this so it makes me want to do it not in the worker or the UI but in the task that maintains the manifest

I would be OK with any solution.

**Comment by pdesoyres-cc** [comment]
You're right @hsablonniere, sorting in the UI would mean importing semver dependency.

But, if we sort only in the manifest, we got the right order in both UI and manifest without importing semver dep.

**Comment by hsablonniere** [comment]
> But, if we sort only in the manifest, we got the right order in both UI and manifest without importing semver dep.

Let's do this, right?

**Comment by florian-sanders-cc** [comment]
Moving the issue to Qualified.
Thanks a lot :heart: 

We'll just have to decide who handles the issue and its priority :+1:
